sudo: required
services:
  - docker

before_install:
  - docker build -t akmaljonsadikov/docker-devops -f Dockerfile.dev .

script:
  - docker run -e CI=true akmaljonsadikov/docker-devops npm run test
